### ISSUE TITLE
Can't fetch API

### ISSUE THREAD

**Issue by phulengo** [aravindballa/random-tw-gradient#1]
```'No 'Access-Control-Allow-Origin'``` blocks the API fetching, using `fetch()` or `axios.get()` always returning network error (Failed to `fetch` due to CORS)! I've tried ```mode: "no-cors"``` but it will return a response with type `opaque`, but I can't get the response data at all. Can you please check the CORS of your API?

**Comment by aravindballa** [comment]
This should help - https://github.com/aravindballa/random-tw-gradient/commit/c40854c0a0d25d229e780b5c206d3b961b25d2aa
